<!DOCTYPE html>
<html lang="pt">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>nextc</title>

     <!-- Favicons -->
  <link href="" rel="icon">
  <link href="" rel="apple-touch-icon">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v5.4.1, mobirise.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <meta name="description" content="">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/css/add.css">

</head>


<body style="overflow: visible;" >
<div id="corpo" >
<?= $this->content() ?>
</div>



    
</body>
</html>
